### ISSUE TITLE
'ERR_REQUIRE_ESM' error

### ISSUE THREAD

**Issue by JasperTheMinecraftDev** [Lorenzo0111/SpigotUpdatesBot#17]
Hi there, I'm getting an error with the latest version:
<html>
<body>

Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/chalk/source/index.js from /utils/Logger.js not supported.
--
2 | Instead change the require of index.js in /utils/Logger.js to a dynamic import() which is available in all CommonJS modules.
3 | at Object.<anonymous> (/utils/Logger.js:1:15)
4 | at Object.<anonymous> (index.js:7:16) {
5 | code: 'ERR_REQUIRE_ESM'

</body>
</html>

**Comment by JasperTheMinecraftDev** [comment]
I reinstalled the bot, the error is now gone but I have another:
found 0 vulnerabilities
/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:134
    } = await this.client.api.gateway.bot.get().catch(error => {
                              ^

TypeError: Cannot read properties of undefined (reading 'gateway')
    at WebSocketManager.connect (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:134:31)
    at Client.login (/home/container/node_modules/discord.js/src/client/Client.js:254:21)
    at Object.<anonymous> (/home/container/index.js:90:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:inter
